// <auto-generated />
namespace DotNetCollege.EFCore.Sample5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InheritanceAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InheritanceAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202108301121547_InheritanceAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
